name: MultiViewClassifier
source: custom
module: models.multi_view_classifier
class: MultiViewClassifier
config_class: MultiViewClassifierConfig
params:
  num_feature: 1
  num_embedding: 64
  num_hidden: 128
  num_head: 4
  num_layers: 3
  num_target: 4
  dropout: 0.1
  
  # Training
  batch_size: 16
  num_epochs: 200
  lr: 0.001
  weight_decay: 0.00001
  l1_scale: 0.0
  l2_scale: 0.01
  
  # Loss
  loss_type: 'ALL'  # 'ALL', 'TDF', 'TD', 'TF', 'DF', 'T', 'D', 'F'
  feature: 'latent'  # 'latent' or 'hidden'
  temperature: 0.07
  lam: 0.0
  
  # Mode
  mode: 'pretrain'  # 'pretrain', 'finetune', 'freeze'
  use_gpu: true
  checkpoint_path: null
  
  # DetectorConfig params
  max_score: 1.0
  enable_calibrator: true
  enable_threshold: true
