# conf/experiments.yaml

# Define all the individual benchmark runs here
runs:

  # # --- Experiment 1: Simple ARIMA on M4 Daily ---
  # - name: "ARIMA_M4_Daily_Baseline"
  #   task: "forecasting"
  #   data: "m4_daily"      # References conf/data/m4_daily.yaml
  #   model: "arima"         # References conf/models/arima.yaml
  #   preprocessor: "no_preproc" # References conf/preprocessor/no_preproc.yaml
  #   metrics: ["rmse", "smape", "mae"]

  #   # --- Experiment 2: Simple ARIMA on M4 Hourly ---
  # - name: "ARIMA_M4_Hourly_Baseline"
  #   task: "forecasting"
  #   data: "m4_hourly"      # References conf/data/m4_hourly.yaml
  #   model: "arima"         # References conf/models/arima.yaml
  #   preprocessor: "no_preproc" # References conf/preprocessor/no_preproc.yaml
  #   metrics: ["rmse", "smape", "mae"]
  
    # --- Experiment 3: Simple ARIMA on EnergyPower ---
  # - name: "ARIMA_EnergyPower_Baseline"
  #   id: 0
  #   task: "forecasting"
  #   data: "energy_power"      # References conf/data/energy_power.yaml
  #   model: "arima"         # References conf/models/arima.yaml
  #   preprocessor: "no_preproc" # References conf/preprocessor/no_preproc.yaml
  #   metrics: ["rmse", "smape", "mae"]

  #--- Experiment 2: DefaultForecaster on M4 with Lagged Features ---
  # - name: "DF_M4_MovingAverage"
  #   task: "forecasting"
  #   data: "m4_daily"       # References conf/data/m4_daily.yaml (New file)
  #   model: "prophet"
  #   preprocessor: "no_preproc"
  #   metrics: ["rmse", "smape", "mae"]

    # --- Test all datasets ---
  # - id: 1
  #   name: "Pretrain SleepEEG_MultiViewClassifier"
  #   task: "classification"
  #   data: "sleep_eeg"
  #   model: "multi_view_classifier"
  #   target: 1
  #   preprocessor: "multi_view_contrastive"
  #   metrics: ["precision", "recall", "f1", "pointwise_precision", "pointwise_recall", "pointwise_f1", "confusion_matrix", "normalized_confusion_matrix"]
  #   overrides:
  #     model:
  #       params:
  #         num_epochs: 200

  # - id: 2
  #   name: "Finetune ECG_MultiViewClassifier"
  #   task: "classification"
  #   data: "ecg"
  #   model: "multi_view_classifier"
  #   target: 1
  #   pretrained_run: 1
  #   skip_training: False
  #   preprocessor: "multi_view_contrastive"
  #   metrics: ["precision", "recall", "f1", "pointwise_precision", "pointwise_recall", "pointwise_f1", "confusion_matrix", "normalized_confusion_matrix"]
  #   overrides:
  #     model:
  #       params:
  #          mode: 'finetune'

  # - id: 3
  #   name: "Ran2025_MultiViewClassifier"
  #   task: "classification"
  #   data: "ran_2025"
  #   model: "multi_view_classifier"
  #   target: 1
  #   preprocessor: "multi_view_contrastive"
  #   metrics: ["precision", "recall", "f1", "pointwise_precision", "pointwise_recall", "pointwise_f1", "confusion_matrix", "normalized_confusion_matrix"]
  #   overrides:
  #     model:
  #       params:
  #         num_epochs: 10

  - id: 4
    name: "Pretrain SleepEEG_MultiViewClassifier"
    task: "classification"
    data: "sleep_eeg"
    model: "multi_view_classifier"
    target: 1
    preprocessor: "multi_view_contrastive"
    metrics: ["precision", "recall", "f1", "accuracy", "auroc_auprc"]
    overrides:
      model:
        params:
          mode: "pretrain"
          num_epochs: 200
          num_target: 5
      metrics:
        auroc_auprc:
          params:
            num_classes: 5

  - id: 5
    name: "Finetune EMG_MultiViewClassifier"
    task: "classification"
    data: "emg"
    model: "multi_view_classifier"
    target: 1
    pretrained_run: 4
    skip_training: False
    preprocessor: "multi_view_contrastive"
    metrics: ["precision", "recall", "f1", "accuracy", "auroc_auprc"]
    overrides:
      model:
        params:
           mode: "finetune"
           batch_size: 16
           num_epochs: 100
           num_target: 3
      metrics:
        auroc_auprc:
          params:
            num_classes: 3
    
  - id: 6
    name: "Finetune EMG_MultiViewClassifier"
    task: "classification"
    data: "emg"
    model: "multi_view_classifier"
    target: 1
    pretrained_run: 4
    skip_training: False
    preprocessor: "multi_view_contrastive"
    metrics: ["precision", "recall", "f1", "accuracy", "auroc_auprc"]
    overrides:
      model:
        params:
           mode: "freeze"
           batch_size: 16
           num_epochs: 100
           num_target: 3
      metrics:
        auroc_auprc:
          params:
            num_classes: 3

  # - id: 7
  #   name: "Pretrain SleepEEG_MultiViewClassifier"
  #   task: "classification"
  #   data: "sleep_eeg"
  #   model: "multi_view_classifier"
  #   target: 1
  #   preprocessor: "multi_view_contrastive"
  #   metrics: ["precision", "recall", "f1", "accuracy", "auroc_auprc"]
  #   overrides:
  #     model:
  #       params:
  #         num_epochs: 10
  #     metrics:
  #       auroc_auprc:
  #         params:
  #           num_classes: 5

  # - id: 8
  #   name: "Finetune EMG_MultiViewClassifier"
  #   task: "classification"
  #   data: "emg"
  #   model: "multi_view_classifier"
  #   target: 1
  #   pretrained_run: 7
  #   skip_training: False
  #   preprocessor: "multi_view_contrastive"
  #   metrics: ["precision", "recall", "f1", "accuracy", "auroc_auprc"]
  #   overrides:
  #     model:
  #       params:
  #          mode: "finetune"
  #          batch_size: 16
  #          num_epochs: 5
  #     metrics:
  #       auroc_auprc:
  #         params:
  #           num_classes: 3