# conf/experiments.yaml

# Define all the individual benchmark runs here
runs:

  # - id: 4
  #   name: "Pretrain SleepEEG_MultiViewClassifier"
  #   task: "classification"
  #   data: "sleep_eeg"
  #   model: "multi_view_classifier"
  #   target: 1
  #   preprocessor: "multi_view_contrastive"
  #   metrics: ["precision", "recall", "f1", "accuracy", "auroc_auprc"]
  #   overrides:
  #     model:
  #       params:
  #         mode: "pretrain"
  #         num_epochs: 200
  #         num_target: 5
  #     metrics:
  #       auroc_auprc:
  #         params:
  #           num_classes: 5

  # - id: 5
  #   name: "Finetune EMG_MultiViewClassifier"
  #   task: "classification"
  #   data: "emg"
  #   model: "multi_view_classifier"
  #   target: 1
  #   pretrained_run: 4
  #   skip_training: False
  #   preprocessor: "multi_view_contrastive"
  #   metrics: ["precision", "recall", "f1", "accuracy", "auroc_auprc"]
  #   overrides:
  #     model:
  #       params:
  #          mode: "finetune"
  #          batch_size: 16
  #          num_epochs: 100
  #          num_target: 3
  #     metrics:
  #       auroc_auprc:
  #         params:
  #           num_classes: 3
    
  # - id: 6
  #   name: "Finetune EMG_MultiViewClassifier"
  #   task: "classification"
  #   data: "emg"
  #   model: "multi_view_classifier"
  #   target: 1
  #   pretrained_run: 4
  #   skip_training: False
  #   preprocessor: "multi_view_contrastive"
  #   metrics: ["precision", "recall", "f1", "accuracy", "auroc_auprc"]
  #   overrides:
  #     model:
  #       params:
  #          mode: "freeze"
  #          batch_size: 16
  #          num_epochs: 100
  #          num_target: 3
  #     metrics:
  #       auroc_auprc:
  #         params:
  #           num_classes: 3

  - id: 104
    name: "Pretrain SleepEEG_MultiViewLogSigClassifier"
    task: "classification"
    data: "sleep_eeg"
    model: "multi_view_log_sig_classifier"
    target: 1
    preprocessor: "multi_view_contrastive"
    metrics: ["precision", "recall", "f1", "accuracy", "auroc_auprc"]
    overrides:
      model:
        params:
          mode: "pretrain"
          num_epochs: 200
          num_target: 5
          views: ["xt", "dx", "xf"]
      metrics:
        auroc_auprc:
          params:
            num_classes: 5

  - id: 105
    name: "Finetune EMG_MultiViewLogSigClassifier"
    task: "classification"
    data: "emg"
    model: "multi_view_log_sig_classifier"
    target: 1
    pretrained_run: 104
    skip_training: False
    preprocessor: "multi_view_contrastive"
    metrics: ["precision", "recall", "f1", "accuracy", "auroc_auprc"]
    overrides:
      model:
        params:
          mode: "finetune"
          batch_size: 16
          num_epochs: 100
          num_target: 3
          views: ["xt", "dx", "xf"]
      metrics:
        auroc_auprc:
          params:
            num_classes: 3

  - id: 106
    name: "Freeze EMG_MultiViewLogSigClassifier"
    task: "classification"
    data: "emg"
    model: "multi_view_log_sig_classifier"
    target: 1
    pretrained_run: 104
    skip_training: False
    preprocessor: "multi_view_contrastive"
    metrics: ["precision", "recall", "f1", "accuracy", "auroc_auprc"]
    overrides:
      model:
        params:
          mode: "freeze"
          batch_size: 16
          num_epochs: 100
          num_target: 3
          views: ["xt", "dx", "xf"]
      metrics:
        auroc_auprc:
          params:
            num_classes: 3

  - id: 107
    name: "RawClassifier"
    task: "classification"
    data: "emg"
    model: "raw_classifier"
    target: 1
    skip_training: False
    preprocessor: "multi_view_contrastive"
    metrics: ["precision", "recall", "f1", "accuracy", "auroc_auprc"]
    overrides:
      model:
        params:
          input_mode: 'raw'
          num_feature: 1
      metrics:
        auroc_auprc:
          params:
            num_classes: 3
  - id: 108
    name: "RawClassifier"
    task: "classification"
    data: "emg"
    model: "raw_classifier"
    target: 1
    skip_training: False
    preprocessor: "multi_view_contrastive"
    metrics: ["precision", "recall", "f1", "accuracy", "auroc_auprc"]
    overrides:
      model:
        params:
          input_mode: 'multi_view'
          num_feature: 1
      metrics:
        auroc_auprc:
          params:
            num_classes: 3


